### ISSUE TITLE
[Bug]: lastDays not include today's data

### ISSUE THREAD

**Issue by KeizerDev** [spatie/filament-simple-stats#5]
### What happened?

I'd like to use this library for my filament projects however when using `last7Days()` or `last30Days()` both are calling the function `lastDays(int $days)` which is using `now()->startOfDay()` to query the days. 

However using `startOfDay()` results in today's data not being included in the data (when using timestamps). 

Is this intended or can it be changed to `endOfDay()` to include today's data?

### How to reproduce the bug

```
SimpleStat::make(User::class)->last30Days()->dailyCount()
```

### Package Version

0.1.3

### PHP Version

8.3.0

### Laravel Version

11.0

**Comment by KeizerDev** [comment]
I assumed this was a bug, if that's the case I already created a PR at #6

**Comment by freekmurze** [comment]
We'll handle this further at #6
